version: '3.8'

services:
  react-app-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_admin
    ports:
      - "5174:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - shared-network-uniselec
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    command: yarn dev --host

networks:
  shared-network-uniselec:
    external: true
